# All values in no of frames
BACKGROUND_COLOR: gray
NO_BLOCK_TRAIN: 1  #ilość bloków tren.
NO_BLOCK_EXP: 2 #ilość bloków eksp.
FRAME_RATE: 60 #???
N_TRIALS_TRAIN: 1
N_TRAILS_EXP: 4 #ilość powtórzeń w bloku
REACTION_KEYS: ["space", 'q', 'p']
RESULTS: [["PART_ID", "TRIAL", "TRAINING", "CORRECT", "CONGRUENT","LATENCY"]]
TIME_BREAK: 1
TIME_FOR_REAST: 30
FIX_CROSS_TIME: 30  #czas miedzy + a bodźcem

FIX_CROSS_COLOR: black
FIX_CROSS_SIZE: 60
STIM_SIZE: 80
STIM_TIME: 240
#STIM_POS_L: (-500.0, 0.0)
#STIM_POS_R: (500.0, 0.0)
STIM_COLOR: red
STIM_BREAK: [30,100] #przedział do losowania czasu miedzy prezentacją bodźca, a nowym bodźcem
